### PR TITLE
Add Content-Security-Policy-Report-Only header

### PR DESCRIPTION
**Pull request by xmorave2**
|    Q          |   A
|-------------- | ------
| New Feature   | yes

### Description
Content-Security-Policy-Report-Only header could be useful when experimenting with policies without impact of you application.

### CODE REVIEW

**Comment by demiankatz** [comment]
Just adding a comment in support of merging this; looks like a safe change to me.

In case anyone is concerned about the failing test, this looks to be the same failure that is affecting master (and which is apparently addressed by #31). It might be a good idea for @xmorave2 to merge the latest master into this PR, though, in case it clarifies the Travis failure messages (since right now, what I'm seeing here looks a little different from what I'm seeing in master).

**Comment by samsonasik** [comment]
please rebase against latest develop branch

**Comment by xmorave2** [comment]
> please rebase against latest develop branch

thanks @samsonasik 

now I use branch develop and I also add sign-off line to my commit

**Comment by xmorave2** [comment]
Is there something what could I do to have this merged? Thanks

**Pull request merged**
