### PR TITLE
Allow laminas/laminas-validator 3.0

### PR DESCRIPTION
**Pull request by marcelthole**
See https://github.com/laminas/laminas-http/pull/83

i accidently updated the source branch and closed the linked PR because there wasn't any diff anymore :/

### CODE REVIEW

**Comment by gsteel** [comment]
v3.0 is not being installed at all: https://github.com/laminas/laminas-http/actions/runs/12123750099/job/33799937150#step:3:78

Can I suggest you try a `composer why-not laminas/laminas-validator 3.0`?

**Comment by froschdesign** [comment]
@gsteel 
```bash
laminas/laminas-uri       2.12.0     requires         laminas/laminas-validator (^2.39)                        
laminas/laminas-validator 3.0.0      requires         laminas/laminas-servicemanager (^4.1.0)                  
laminas/laminas-http      2.21.x-dev does not require laminas/laminas-servicemanager (but 3.23.0 is installed)
```

**Comment by gsteel** [comment]
Aye, so laminas-uri is the blocker - we'll have to update it with v3.0 support first

**Comment by marcelthole** [comment]
I created the PR for laminas-uri to support laminas-validator 3 - https://github.com/laminas/laminas-uri/pull/24

**Review by Slamdunk — APPROVED** [review]

**Comment by gsteel** [comment]
Now URI is released, can you please refresh composer.lock and re-push so we can see CI installing v3?

**Comment by marcelthole** [comment]
>   - Downloading laminas/laminas-validator (3.0.1)

Yes, version 3.0.1 could be installed

**Review by gsteel — APPROVED** [review]
Thank you @marcelthole :)

**Pull request merged**
