### PR TITLE
Allow PHP 8.4

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

**Comment by fezfez** [comment]
@gsteel ci seem to be broken.. :/

**Comment by gsteel** [comment]
CI looks fine. Tests are broken though. The error looks consistent. Possibly something changed in libcurl. 🤷‍♂️

**Comment by fezfez** [comment]
> CI looks fine. Tests are broken though. The error looks consistent. Possibly something changed in libcurl. 🤷‍♂️

The test even fail in https://github.com/laminas/laminas-http/pull/83 IMO it's not related to this pr

**Review by gsteel — APPROVED** [review]
Thank you @fezfez - You help is much appreciated :)

**Pull request merged**
